{% set name = "flake8-broken-line" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-broken-line-{{ version }}.tar.gz
  sha256: 7c98de9dd1385b71e888709c7f2aee3f0514107ecb5875bc95d0c03392191c97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - flake8 >=3.5,<6
    - python >=3.6

test:
  commands:
    - pip check
    - flake8 --version | grep flake8-broken-line
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/wemake-services/flake8-broken-line
  summary: Flake8 plugin to forbid backslashes for line breaks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
